services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service  # Moved here, outside of `build`
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/UserManagement_Service?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - bank-network  # Referencing the network correctly

  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UserManagement_Service
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bank-network  # Referencing the network correctly

networks:
  bank-network:
    driver: bridge  # Defining the network at the root level

volumes:
  db_data:
